#!/usr/bin/env web exec
# encoding: utf-8

version: 1

root:
	class: web.app.contentment.controller:ContentmentRoot

extensions:
	analytics:
	template:
	cast:
	mongoengine:
		uri: mongo://localhost/contentment
	contentment:

logging:
	version: 1
	
	handlers:
		console:
			class: logging.StreamHandler
			level: DEBUG
			stream: ext://sys.stdout
		central:
			class: marrow.contentment.util.logging.MongoEngineLogger
			args: []
	
	loggers:
		root:
			level: INFO
			handlers: [console, central]
		
		webcore:
			level: DEBUG
			handlers: [console]
			